### ISSUE TITLE
FA Extender download feature doesn't work on new UI

### ISSUE THREAD

**Issue by vahaala** [AndrewNeo/faextender#37] opened 2015-06-17 20:01 UTC
I'm not really sure if the addon is still in development, I hope it is. But cutting to the point - somehow the new, beta UI layout of FA renders the addon pretty much useless. Pictures don't download automatically, and there's no option to download those aside from the usual one that exists by default. On the old layout it simply works like it used to.

**Comment by AndrewNeo** [comment] 2015-06-25 09:47
Dupe of #35

**Closed by AndrewNeo** 2015-06-25 09:47 UTC
